name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

  runTestSuite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run test suite
      env:
        GRADLE_OPTS: "-Xmx2048m"
      run: ./gradlew rTS --no-daemon

  publishDockerImage:
    needs: [build, runTestSuite]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username michelkraemer --password-stdin
      env:
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build Docker image
      run: docker build -t michelkraemer/citeproc-java:latest .
    - name: Push to Docker Hub
      run: docker push michelkraemer/citeproc-java:latest
